fix(ci): support releases with no automatic changelog

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -149,7 +149,7 @@ jobs:
 
             echo "${CIRCLE_TAG}" > CHANGELOG.md
             echo "" >> CHANGELOG.md
-            git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' | grep "${PROJECT}" >> CHANGELOG.md
+            git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' | grep "${PROJECT}" || echo "# could not detect changes" >> CHANGELOG.md
       - run: hub release create -FCHANGELOG.md "${CIRCLE_TAG}"
 
   py3to2:
